export const TIMINGS_REQUEST = 'TIMINGS_REQUEST';
export const TIMINGS_SUCCESS = 'TIMINGS_SUCCESS';
export const TIMINGS_FAILURE = 'TIMINGS_FAILURE';

export const CANCHAS_REQUEST = 'CANCHAS_REQUEST';
export const CANCHAS_SUCCESS = 'CANCHAS_SUCCESS';
export const CANCHAS_FAILURE = 'CANCHAS_FAILURE';